services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1  # Reliable Zookeeper image
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-net  # Attach to the custom network

  kafka:
    image: confluentinc/cp-kafka:latest  # Use a compatible Kafka image
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - kafka-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messenger-app
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092  # Ensure Kafka connection matches
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
